<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    public function run(): void
    {
$items = [
    [
        'code' => 1,
        'name' => 'سگریت موند',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰ قطی ',
        'smallest_unit' => 'قطی',
        'size' => '',
        'wholesale_price' => '180',
        'retail_price' => '20',
    ],
    [
        'code' => 2,
        'name' => 'سگریت پین کلان ',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰ قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'کلان',
        'wholesale_price' => '',
        'retail_price' => '',
    ],
    [
        'code' => 3,
        'name' => 'سگریت ایسی بلک',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '510',
        'retail_price' => '60',
    ],
    [
        'code' => 4,
        'name' => 'سگریت ملانو سرخ ',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '200',
        'retail_price' => '20',
    ],
    [
        'code' => 5,
        'name' => 'سگریت جاپانی ',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '400',
        'retail_price' => '50',
    ],
    [
        'code' => 6,
        'name' => 'سگریت ملانوسیا',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '360',
        'retail_price' => '40',
    ],
    [
        'code' => 7,
        'name' => 'سگریت ملانو هفت رنگ',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '160',
        'retail_price' => '20',
    ],
    [
        'code' => 8,
        'name' => 'سگریت ملانو سفید ',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '360',
        'retail_price' => '40',
    ],
    [
        'code' => 9,
        'name' => 'سگریت پلاتنیوم ',
        'packing' => 'باکس ',
        'packaging_quantity' => '۱۰ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => '',
        'wholesale_price' => '160',
        'retail_price' => '20',
    ],
    [
        'code' => 10,
        'name' => 'روغن مایع روسی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳ بوتل ',
        'smallest_unit' => '۵ لیتر ',
        'size' => '۵ لیتر ',
        'wholesale_price' => '1720',
        'retail_price' => '580',
    ],
    [
        'code' => 11,
        'name' => 'روغن مایع سایمون',
        'packing' => 'پیپ',
        'packaging_quantity' => 'پیپ',
        'smallest_unit' => '۱۸  لیتر ',
        'size' => 'پیپ',
        'wholesale_price' => '2000',
        'retail_price' => '2000',
    ],
    [
        'code' => 12,
        'name' => 'روغن ۱۰ لیتر ',
        'packing' => 'بوشکه ',
        'packaging_quantity' => 'بوشکه ',
        'smallest_unit' => '۱۰ لیتر ',
        'size' => 'بوشکه ',
        'wholesale_price' => '1050',
        'retail_price' => '1050',
    ],
    [
        'code' => 13,
        'name' => 'روغن مایع سی گل ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴ بوتل ',
        'smallest_unit' => '۲۰ لیتر ',
        'size' => 'کارتن ',
        'wholesale_price' => '2200',
        'retail_price' => '560',
    ],
    [
        'code' => 14,
        'name' => 'شیرخرما پگاه ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ دانه ',
        'smallest_unit' => 'قطی ',
        'size' => 'بسته ',
        'wholesale_price' => '480',
        'retail_price' => '20',
    ],
    [
        'code' => 15,
        'name' => 'شیر کوثر ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ دانه ',
        'smallest_unit' => 'قطی ',
        'size' => '  بسته ',
        'wholesale_price' => '360',
        'retail_price' => '20',
    ],
    [
        'code' => 16,
        'name' => 'شیر های ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ دانه ',
        'smallest_unit' => 'قطی ',
        'size' => 'بسته ',
        'wholesale_price' => '330',
        'retail_price' => '20',
    ],
    [
        'code' => 17,
        'name' => 'خرما مضافتی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => 'کارتن ',
        'wholesale_price' => '1150',
        'retail_price' => '100',
    ],
    [
        'code' => 18,
        'name' => 'چایی سیا شاه پسند',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۵۰ کلیو ',
        'smallest_unit' => 'کلیو ',
        'size' => '',
        'wholesale_price' => '‍۱۵۰۰۰ ',
        'retail_price' => '320',
    ],
    [
        'code' => 19,
        'name' => 'چایی سبز  تابان ',
        'packing' => 'بوجی ',
        'packaging_quantity' => 'یک ',
        'smallest_unit' => 'کلیو ',
        'size' => '',
        'wholesale_price' => '1800',
        'retail_price' => '380',
    ],
    [
        'code' => 20,
        'name' => 'چایی سیا کنیا ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۵۰ کلیو ',
        'smallest_unit' => 'کلیو ',
        'size' => 'بوجی ',
        'wholesale_price' => '13000',
        'retail_price' => '270',
    ],
    [
        'code' => 21,
        'name' => 'چایی سبز الحسان ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۳۵ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'بوجی ',
        'wholesale_price' => '9450',
        'retail_price' => '280',
    ],
    [
        'code' => 22,
        'name' => 'نخود گل ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۳۵ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'بوجی ',
        'wholesale_price' => '3900',
        'retail_price' => '120',
    ],
    [
        'code' => 23,
        'name' => 'سیمیان ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۴۰ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'بوجی ',
        'wholesale_price' => '3200',
        'retail_price' => '90',
    ],
    [
        'code' => 24,
        'name' => 'ملایی های ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '560',
        'retail_price' => '25',
    ],
    [
        'code' => 25,
        'name' => 'کماندو کلان ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بسته ',
        'wholesale_price' => '195',
        'retail_price' => '20',
    ],
    [
        'code' => 26,
        'name' => 'کماندو خورد ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بسته ',
        'wholesale_price' => '200',
        'retail_price' => '10',
    ],
    [
        'code' => 27,
        'name' => 'هیت گاز دار ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => 'بسته ',
        'wholesale_price' => '590',
        'retail_price' => '30',
    ],
    [
        'code' => 28,
        'name' => 'هیت ساده ',
        'packing' => ' بسته ',
        'packaging_quantity' => '۲۴ قطی ',
        'smallest_unit' => 'قطی ',
        'size' => 'بسته ',
        'wholesale_price' => '590',
        'retail_price' => '30',
    ],
    [
        'code' => 29,
        'name' => 'ایکسبول ساده ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی',
        'smallest_unit' => 'قطی ',
        'size' => '‍بسته ',
        'wholesale_price' => '560',
        'retail_price' => '30',
    ],
    [
        'code' => 30,
        'name' => 'ایکسبول گاز دار ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '560',
        'retail_price' => '30',
    ],
    [
        'code' => 31,
        'name' => 'رانی رویال ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '510',
        'retail_price' => '30',
    ],
    [
        'code' => 32,
        'name' => 'رانی پاردایس ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '510',
        'retail_price' => '30',
    ],
    [
        'code' => 33,
        'name' => 'هپی مسیف خورد ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '580',
        'retail_price' => '30',
    ],
    [
        'code' => 34,
        'name' => 'هپی مسیف کلان ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '580',
        'retail_price' => '50',
    ],
    [
        'code' => 35,
        'name' => 'پپسی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ قطی',
        'smallest_unit' => 'قطی',
        'size' => 'بسته ',
        'wholesale_price' => '370',
        'retail_price' => '20',
    ],
    [
        'code' => 36,
        'name' => 'مکرانی تک کلان اول ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳۰ پاکت‍',
        'smallest_unit' => 'پاکت',
        'size' => '۵۰۰گرام‍',
        'wholesale_price' => '1240',
        'retail_price' => '45',
    ],
    [
        'code' => 37,
        'name' => 'مکرانی  تک کلان',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳۰ پاکت‍',
        'smallest_unit' => 'پاکت ',
        'size' => '۵۰۰گرام‍',
        'wholesale_price' => '1120',
        'retail_price' => '50',
    ],
    [
        'code' => 38,
        'name' => 'مکرانی تک خورد ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴پاکت',
        'smallest_unit' => 'پاکت',
        'size' => '۴۰۰ گرام ',
        'wholesale_price' => '860',
        'retail_price' => '40',
    ],
    [
        'code' => 39,
        'name' => 'مکرانی جهان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => '۷۰۰گرام ',
        'wholesale_price' => '960',
        'retail_price' => '50',
    ],
    [
        'code' => 40,
        'name' => 'مکرانی زر ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰ پاکت ',
        'smallest_unit' => 'پاکت',
        'size' => '۷۰۰گرام ',
        'wholesale_price' => '850',
        'retail_price' => '45',
    ],
    [
        'code' => 41,
        'name' => 'مکرانی تک برمه ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => '۴۰۰گرام',
        'wholesale_price' => '850',
        'retail_price' => '45',
    ],
    [
        'code' => 42,
        'name' => 'مکرانی تک برمه سبزی دار ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => '۴۰۰گرام',
        'wholesale_price' => '900',
        'retail_price' => '50',
    ],
    [
        'code' => 43,
        'name' => 'مکرانی برمه ای بوجی ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1000',
        'retail_price' => '60',
    ],
    [
        'code' => 44,
        'name' => 'سویا سبحان ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۲ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '700',
        'retail_price' => '80',
    ],
    [
        'code' => 45,
        'name' => 'انار ۲۴ عدد نیک',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => '۲۰۰ سی سی',
        'wholesale_price' => '140',
        'retail_price' => '10',
    ],
    [
        'code' => 46,
        'name' => 'چاکلیت ریکس ایرانی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1620',
        'retail_price' => '150',
    ],
    [
        'code' => 47,
        'name' => 'چاکلیت لوکس ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '380',
        'retail_price' => '50',
    ],
    [
        'code' => 48,
        'name' => 'چاکلیت ادرین ایرانی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1720',
        'retail_price' => '160',
    ],
    [
        'code' => 49,
        'name' => 'چاکلیت ایدین شیرخامه ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1650',
        'retail_price' => '160',
    ],
    [
        'code' => 50,
        'name' => 'چاکلیت آیدین نارگیل',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1750',
        'retail_price' => '170',
    ],
    [
        'code' => 51,
        'name' => 'گاکلیت لاله ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1250',
        'retail_price' => '120',
    ],
    [
        'code' => 52,
        'name' => 'پودر نابود ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴درجن',
        'smallest_unit' => 'قطی ',
        'size' => 'قطی',
        'wholesale_price' => '280',
        'retail_price' => '30',
    ],
    [
        'code' => 53,
        'name' => 'ساجیق اسپوت',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸بسته',
        'smallest_unit' => 'بسته ',
        'size' => 'دانه',
        'wholesale_price' => '480',
        'retail_price' => '10',
    ],
    [
        'code' => 54,
        'name' => 'ساجیق افضلی کلان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'دانه',
        'wholesale_price' => '1050',
        'retail_price' => '280',
    ],
    [
        'code' => 55,
        'name' => 'ساجیق افضلی خورد ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'دانه ',
        'wholesale_price' => '1000',
        'retail_price' => '170',
    ],
    [
        'code' => 56,
        'name' => 'ساجیق هیل دار',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۵۰بسته',
        'smallest_unit' => 'بسته ',
        'size' => 'دانه',
        'wholesale_price' => '3650',
        'retail_price' => '75',
    ],
    [
        'code' => 57,
        'name' => 'ساجیق جام جهانی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'دانه',
        'wholesale_price' => '1150',
        'retail_price' => '65',
    ],
    [
        'code' => 58,
        'name' => 'جوس عالی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '160',
        'retail_price' => '5',
    ],
    [
        'code' => 59,
        'name' => 'جوس مانی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '145',
        'retail_price' => '5',
    ],
    [
        'code' => 60,
        'name' => 'جوس پاکستانی رسنا',
        'packing' => 'بسته ',
        'packaging_quantity' => '۳۶پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '160',
        'retail_price' => '10',
    ],
    [
        'code' => 61,
        'name' => 'جوس خورد پاکستانی رسنا',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '100',
        'retail_price' => '5',
    ],
    [
        'code' => 62,
        'name' => 'انارکلان شفا',
        'packing' => 'بسته ',
        'packaging_quantity' => '۶ بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '260',
        'retail_price' => '60',
    ],
    [
        'code' => 63,
        'name' => 'انار خورد شفا ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '110',
        'retail_price' => '20',
    ],
    [
        'code' => 64,
        'name' => 'انار میانه شفا',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => ' بوتل',
        'wholesale_price' => '220',
        'retail_price' => '30',
    ],
    [
        'code' => 65,
        'name' => 'گالگیت کلان ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲ قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '600',
        'retail_price' => '60',
    ],
    [
        'code' => 66,
        'name' => 'گالگلیت خورد ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '400',
        'retail_price' => '40',
    ],
    [
        'code' => 67,
        'name' => 'پودر ایفی ۱۲ کلیویی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => 'کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1350',
        'retail_price' => '150',
    ],
    [
        'code' => 68,
        'name' => 'روغن رامین پپ',
        'packing' => 'پیپ',
        'packaging_quantity' => 'پیپ',
        'smallest_unit' => 'پیپ',
        'size' => 'پیپ',
        'wholesale_price' => '۱۸۵۰‍',
        'retail_price' => '1850',
    ],
    [
        'code' => 69,
        'name' => 'مربا میانه آمو',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => '۲۵۰ سی سی',
        'wholesale_price' => '350',
        'retail_price' => '50',
    ],
    [
        'code' => 70,
        'name' => 'مربا کلان آمو',
        'packing' => 'بسته ',
        'packaging_quantity' => '۶ بوتل',
        'smallest_unit' => '‍ بوتل',
        'size' => '۵۰۰سی سی ',
        'wholesale_price' => '420',
        'retail_price' => '100',
    ],
    [
        'code' => 71,
        'name' => 'لی لی گل نخودی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '250',
        'retail_price' => '5',
    ],
    [
        'code' => 72,
        'name' => 'خندان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '250',
        'retail_price' => '5',
    ],
    [
        'code' => 73,
        'name' => 'روغن مایع خورد ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۵ بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '1240',
        'retail_price' => '100',
    ],
    [
        'code' => 74,
        'name' => 'کیک ۳۶ ناب',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳۶ دانه',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '140',
        'retail_price' => '10',
    ],
    [
        'code' => 75,
        'name' => 'کیک۶۰ ناب',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶۰ دانه',
        'smallest_unit' => 'دانه',
        'size' => ' دانه',
        'wholesale_price' => '140',
        'retail_price' => '5',
    ],
    [
        'code' => 76,
        'name' => 'کیک بابا ۲ ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶۰ دانه',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '260',
        'retail_price' => '5',
    ],
    [
        'code' => 77,
        'name' => 'کیک ۳۰ عدد پدیده',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳۰ دانه',
        'smallest_unit' => 'دانه',
        'size' => ' دانه',
        'wholesale_price' => '200',
        'retail_price' => '10',
    ],
    [
        'code' => 78,
        'name' => 'کیک ۱۸ عدد پدیده',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۸ دانه',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '260',
        'retail_price' => '20',
    ],
    [
        'code' => 79,
        'name' => 'کیک سه لایه پدیده ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '170',
        'retail_price' => '10',
    ],
    [
        'code' => 80,
        'name' => 'کیک حلقه ای ۲۴عدد',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '200',
        'retail_price' => '10',
    ],
    [
        'code' => 81,
        'name' => 'تخمک دوم',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۵ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'خورد',
        'wholesale_price' => '600',
        'retail_price' => '15',
    ],
    [
        'code' => 82,
        'name' => 'تخمک دوم',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'خورد',
        'wholesale_price' => '1200',
        'retail_price' => '15',
    ],
    [
        'code' => 83,
        'name' => 'تخمک اول ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۰ کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'خورد ',
        'wholesale_price' => '1750',
        'retail_price' => '20',
    ],
    [
        'code' => 84,
        'name' => 'گلدن لایف کلان',
        'packing' => 'بسته ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '250',
        'retail_price' => '60',
    ],
    [
        'code' => 85,
        'name' => 'گلان لایف بوتل خورد ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '105',
        'retail_price' => '10',
    ],
    [
        'code' => 86,
        'name' => 'پمپرس سلیپی',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '1520',
        'retail_price' => '80',
    ],
    [
        'code' => 87,
        'name' => 'ماست نگاه',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '450',
        'retail_price' => '50',
    ],
    [
        'code' => 88,
        'name' => 'عم خورد خورد شفا ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '150',
        'retail_price' => '20',
    ],
    [
        'code' => 89,
        'name' => 'عم میانه شفا  ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بسته ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '250',
        'retail_price' => '30',
    ],
    [
        'code' => 90,
        'name' => 'عم کلان شفا ',
        'packing' => 'بسته ',
        'packaging_quantity' => ' ۶ بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '250',
        'retail_price' => '50',
    ],
    [
        'code' => 91,
        'name' => 'عم خورد ۲۴ عدد هراتی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '160',
        'retail_price' => '10',
    ],
    [
        'code' => 92,
        'name' => 'عم خورد ۲۴عدد غزنی',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '140',
        'retail_price' => '10',
    ],
    [
        'code' => 93,
        'name' => 'شامپو پرژک ایرانی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '1550',
        'retail_price' => '90',
    ],
    [
        'code' => 94,
        'name' => 'شامپو شبنم میانه ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۶بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '780',
        'retail_price' => '60',
    ],
    [
        'code' => 95,
        'name' => 'شامپو شبنم کلان',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '600',
        'retail_price' => '90',
    ],
    [
        'code' => 96,
        'name' => 'شامپو رخسار ایرانی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '850',
        'retail_price' => '100',
    ],
    [
        'code' => 97,
        'name' => 'شامپو میامی زیتون',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '980',
        'retail_price' => '100',
    ],
    [
        'code' => 98,
        'name' => 'شامپومیامی میانه',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '820',
        'retail_price' => '70',
    ],
    [
        'code' => 99,
        'name' => 'شامپو امیران پاکتی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بسته',
        'smallest_unit' => 'بسته ',
        'size' => 'بسته ',
        'wholesale_price' => '560',
        'retail_price' => '60',
    ],
    [
        'code' => 100,
        'name' => 'باطری قلیمی زرد',
        'packing' => 'قطی',
        'packaging_quantity' => '۱۵ جوره',
        'smallest_unit' => 'جوره',
        'size' => 'جوره',
        'wholesale_price' => '280',
        'retail_price' => '20',
    ],
    [
        'code' => 101,
        'name' => 'باطری کلان ',
        'packing' => 'قطی',
        'packaging_quantity' => '۱۲جوره',
        'smallest_unit' => 'جوره',
        'size' => 'جوره',
        'wholesale_price' => '420',
        'retail_price' => '50',
    ],
    [
        'code' => 102,
        'name' => 'پنیر های ۵۰ گرام',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '210',
        'retail_price' => '10',
    ],
    [
        'code' => 103,
        'name' => 'پنیر های ‍۱۰۰ گرام',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '420',
        'retail_price' => '20',
    ],
    [
        'code' => 104,
        'name' => 'دستمال گلبرگ قطی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴قطی',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '1300',
        'retail_price' => '60',
    ],
    [
        'code' => 105,
        'name' => 'دستمال رول شبنم',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ رول',
        'smallest_unit' => 'رول',
        'size' => 'رول',
        'wholesale_price' => '1150',
        'retail_price' => '100',
    ],
    [
        'code' => 106,
        'name' => 'دستمال فاین رول ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲رول',
        'smallest_unit' => 'رول',
        'size' => 'رول',
        'wholesale_price' => '900',
        'retail_price' => '90',
    ],
    [
        'code' => 107,
        'name' => 'دستمال ۶۰۰ برگ گلبرک',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۰بسته',
        'smallest_unit' => 'بسته ',
        'size' => 'بسته ',
        'wholesale_price' => '1600',
        'retail_price' => '80',
    ],
    [
        'code' => 108,
        'name' => 'کاغذ تشناب گلبرک',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۰ بسته',
        'smallest_unit' => 'بسته ',
        'size' => 'بسته ',
        'wholesale_price' => '1100',
        'retail_price' => '110',
    ],
    [
        'code' => 109,
        'name' => 'پنیر پکاه ۱۰۰ گرام',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۵شانه',
        'smallest_unit' => 'شانه',
        'size' => 'دانه',
        'wholesale_price' => '2700',
        'retail_price' => '25',
    ],
    [
        'code' => 110,
        'name' => 'کره ایرانی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶قطی',
        'smallest_unit' => 'قطی',
        'size' => 'دانه',
        'wholesale_price' => '450',
        'retail_price' => '10',
    ],
    [
        'code' => 111,
        'name' => 'اتک کلان ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ دانه',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '750',
        'retail_price' => '70',
    ],
    [
        'code' => 112,
        'name' => 'اتک خورد ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴دانه',
        'smallest_unit' => 'دانه',
        'size' => 'دانه',
        'wholesale_price' => '670',
        'retail_price' => '40',
    ],
    [
        'code' => 113,
        'name' => 'آب خورد زلال',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '70',
        'retail_price' => '10',
    ],
    [
        'code' => 114,
        'name' => 'آب کلان زلال',
        'packing' => 'بسته ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '80',
        'retail_price' => '20',
    ],
    [
        'code' => 115,
        'name' => 'چاکلیت مینو',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1750',
        'retail_price' => '160',
    ],
    [
        'code' => 116,
        'name' => 'صابون نویدمالزیا خورد ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴گلوچه',
        'smallest_unit' => 'کلوچه',
        'size' => 'کلوچه',
        'wholesale_price' => '450',
        'retail_price' => '20',
    ],
    [
        'code' => 117,
        'name' => 'صابون نوید مالیزیا کلان',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰کلوچه',
        'smallest_unit' => 'کلوچه',
        'size' => 'کلوچه',
        'wholesale_price' => '520',
        'retail_price' => '30',
    ],
    [
        'code' => 118,
        'name' => 'صابون کاج',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴کلوچه',
        'smallest_unit' => 'کلوچه',
        'size' => 'کلوچه',
        'wholesale_price' => '500',
        'retail_price' => '25',
    ],
    [
        'code' => 119,
        'name' => 'صابون لباس شویی شکوه',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴۰کلوچه',
        'smallest_unit' => 'کلوچه',
        'size' => 'کلوچه',
        'wholesale_price' => '540',
        'retail_price' => '20',
    ],
    [
        'code' => 120,
        'name' => 'قهوه بوتل محمود',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '2100',
        'retail_price' => '360',
    ],
    [
        'code' => 121,
        'name' => 'چایی سیا الطیور ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۶بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '1380',
        'retail_price' => '100',
    ],
    [
        'code' => 122,
        'name' => 'لیمونات ۲۴ عدد',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '180',
        'retail_price' => '10',
    ],
    [
        'code' => 123,
        'name' => 'لیمونات شیشه',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '300',
        'retail_price' => '30',
    ],
    [
        'code' => 124,
        'name' => 'برنج ۱۰کلیوی ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1250',
        'retail_price' => '130',
    ],
    [
        'code' => 125,
        'name' => 'برنج۲۰کلیوی حاجی قربان',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '۲۴۰۰‍',
        'retail_price' => '120',
    ],
    [
        'code' => 126,
        'name' => 'زیره قطی',
        'packing' => 'بوتل',
        'packaging_quantity' => '۱۰۰گرام',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '60',
        'retail_price' => '60',
    ],
    [
        'code' => 127,
        'name' => 'دال متر',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1050',
        'retail_price' => '‍۸۰',
    ],
    [
        'code' => 128,
        'name' => 'دال ماش',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1560',
        'retail_price' => '95',
    ],
    [
        'code' => 129,
        'name' => 'نخود خام ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1620',
        'retail_price' => '100',
    ],
    [
        'code' => 130,
        'name' => 'لوبیا وطنی ',
        'packing' => 'سیر',
        'packaging_quantity' => '۷کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '500',
        'retail_price' => '80',
    ],
    [
        'code' => 131,
        'name' => 'لوبیا ترکمنی اول ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1750',
        'retail_price' => '100',
    ],
    [
        'code' => 132,
        'name' => 'لوبیا ترکمنی وطنی ',
        'packing' => 'سیر',
        'packaging_quantity' => '۷کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '600',
        'retail_price' => '95',
    ],
    [
        'code' => 133,
        'name' => 'ماهی کباب ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '330',
        'retail_price' => '5',
    ],
    [
        'code' => 134,
        'name' => 'بسکویت بیکری',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۹۶ عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '2000',
        'retail_price' => '25',
    ],
    [
        'code' => 135,
        'name' => 'بسکویت پرنس',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۹۶ عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '2000',
        'retail_price' => '25',
    ],
    [
        'code' => 136,
        'name' => 'ریکا ایفی ۱لیتر ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '960',
        'retail_price' => '100',
    ],
    [
        'code' => 137,
        'name' => 'کتابچه چینایی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴درجن',
        'smallest_unit' => 'درجن',
        'size' => 'دانه',
        'wholesale_price' => '1540',
        'retail_price' => '65',
    ],
    [
        'code' => 138,
        'name' => 'کتابچه اندونزی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲درجن',
        'smallest_unit' => 'درجن',
        'size' => 'دانه',
        'wholesale_price' => '1150',
        'retail_price' => '110',
    ],
    [
        'code' => 139,
        'name' => 'استینگ آهنی',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '600',
        'retail_price' => '30',
    ],
    [
        'code' => 140,
        'name' => 'استینگ بوتلی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۰بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '360',
        'retail_price' => '20',
    ],
    [
        'code' => 141,
        'name' => 'شامپو شاف ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '960',
        'retail_price' => '90',
    ],
    [
        'code' => 142,
        'name' => 'شامپو زینگ ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '2000',
        'retail_price' => '100',
    ],
    [
        'code' => 143,
        'name' => 'ورق ای فور',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۵بسته ',
        'smallest_unit' => 'بسته ',
        'size' => 'بسته ',
        'wholesale_price' => '250',
        'retail_price' => '250',
    ],
    [
        'code' => 144,
        'name' => 'پودر میوه کلاب ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴قطی',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '1540',
        'retail_price' => '70',
    ],
    [
        'code' => 145,
        'name' => 'وازلین کلان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1600',
        'retail_price' => '80',
    ],
    [
        'code' => 146,
        'name' => 'وازلین پنک کلان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '560',
        'retail_price' => '50',
    ],
    [
        'code' => 147,
        'name' => 'وازلین ملمی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '420',
        'retail_price' => '10',
    ],
    [
        'code' => 148,
        'name' => 'قند سیا ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۴کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1850',
        'retail_price' => '90',
    ],
    [
        'code' => 149,
        'name' => 'روغن پاکت',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۶پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '1240',
        'retail_price' => '80',
    ],
    [
        'code' => 150,
        'name' => 'نمک ایرانی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '320',
        'retail_price' => '20',
    ],
    [
        'code' => 151,
        'name' => 'نوشابه خورد ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '100',
        'retail_price' => '10',
    ],
    [
        'code' => 152,
        'name' => 'عم خورد ۵',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '100',
        'retail_price' => '5',
    ],
    [
        'code' => 153,
        'name' => 'انار خورد ۵',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '100',
        'retail_price' => '5',
    ],
    [
        'code' => 154,
        'name' => 'شکر ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۴۹کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => ' کلیو',
        'wholesale_price' => '2550',
        'retail_price' => '55',
    ],
    [
        'code' => 155,
        'name' => 'نمک زرد',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۴کلیو',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '280',
        'retail_price' => '20',
    ],
    [
        'code' => 156,
        'name' => 'نمک سبز ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '350',
        'retail_price' => '20',
    ],
    [
        'code' => 157,
        'name' => 'نمک نانبایی ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '360',
        'retail_price' => '360',
    ],
    [
        'code' => 158,
        'name' => 'کشمش سرخ ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۵۶کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '6800',
        'retail_price' => '130',
    ],
    [
        'code' => 159,
        'name' => 'کشمش سبز',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴.۵کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '4130',
        'retail_price' => '180',
    ],
    [
        'code' => 160,
        'name' => 'انرژی الکوزی زرد',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '560',
        'retail_price' => '30',
    ],
    [
        'code' => 161,
        'name' => 'خرما خشک',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۰کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1200',
        'retail_price' => '120',
    ],
    [
        'code' => 162,
        'name' => 'مایع دست شویی ایفی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '650',
        'retail_price' => '60',
    ],
    [
        'code' => 163,
        'name' => 'شیشه پاک ایفی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '650',
        'retail_price' => '60',
    ],
    [
        'code' => 164,
        'name' => 'دلستر ایرانی',
        'packing' => 'بسته ',
        'packaging_quantity' => ' ۱۲بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '420',
        'retail_price' => '40',
    ],
    [
        'code' => 165,
        'name' => 'وازلین لباس ایفی ',
        'packing' => 'بسته ',
        'packaging_quantity' => ' ۶بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '620',
        'retail_price' => '110',
    ],
    [
        'code' => 166,
        'name' => 'شیر نتروسی',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '300',
        'retail_price' => '20',
    ],
    [
        'code' => 167,
        'name' => 'ملایی عسلی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴ عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '730',
        'retail_price' => '40',
    ],
    [
        'code' => 168,
        'name' => 'ککو ایکس ۵ ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶قطی',
        'smallest_unit' => 'قطی',
        'size' => 'عدد',
        'wholesale_price' => '1550',
        'retail_price' => '260',
    ],
    [
        'code' => 169,
        'name' => 'ککونانی ۵ فروش ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶قطی',
        'smallest_unit' => 'قطی',
        'size' => 'عدد',
        'wholesale_price' => '720',
        'retail_price' => '130',
    ],
    [
        'code' => 170,
        'name' => 'ککو نانی ۲ ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶قطی',
        'smallest_unit' => 'قطی',
        'size' => 'عدد',
        'wholesale_price' => '960',
        'retail_price' => '165',
    ],
    [
        'code' => 171,
        'name' => 'ککو ایدین',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶قطی',
        'smallest_unit' => 'قطی',
        'size' => 'عدد',
        'wholesale_price' => '600',
        'retail_price' => '100',
    ],
    [
        'code' => 172,
        'name' => 'صابون رویال دست ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶ درجن',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '1680',
        'retail_price' => '300',
    ],
    [
        'code' => 173,
        'name' => 'صابون خورد حمام',
        'packing' => 'کارتن ',
        'packaging_quantity' => 'کارتن',
        'smallest_unit' => 'کارتن',
        'size' => 'کارتن ',
        'wholesale_price' => '2300',
        'retail_price' => '2300',
    ],
    [
        'code' => 174,
        'name' => 'صابون دست شکوه ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶درجن',
        'smallest_unit' => 'درجن',
        'size' => 'عدد',
        'wholesale_price' => '1300',
        'retail_price' => '220',
    ],
    [
        'code' => 175,
        'name' => 'شیرپسته',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '380',
        'retail_price' => '20',
    ],
    [
        'code' => 176,
        'name' => 'روغن ۳لیتر ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '2100',
        'retail_price' => '350',
    ],
    [
        'code' => 177,
        'name' => 'گوگرد کلان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۰گرز',
        'smallest_unit' => 'گرز',
        'size' => 'گرز',
        'wholesale_price' => '400',
        'retail_price' => '60',
    ],
    [
        'code' => 178,
        'name' => 'صفره یکبار مصرف ',
        'packing' => 'عدد',
        'packaging_quantity' => 'عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '50',
        'retail_price' => '50',
    ],
    [
        'code' => 179,
        'name' => 'صفره پاک کن',
        'packing' => 'بسته ',
        'packaging_quantity' => '۴۰عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '280',
        'retail_price' => '10',
    ],
    [
        'code' => 180,
        'name' => 'قلم گلد',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴قطی',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '3840',
        'retail_price' => '170',
    ],
    [
        'code' => 181,
        'name' => 'شیر کود دی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => ' عدد',
        'size' => 'عدد',
        'wholesale_price' => '300',
        'retail_price' => '20',
    ],
    [
        'code' => 182,
        'name' => 'سن ایچ کلان ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲عدد',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '950',
        'retail_price' => '90',
    ],
    [
        'code' => 183,
        'name' => 'سن ایچ خورد ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۳۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '440',
        'retail_price' => '20',
    ],
    [
        'code' => 184,
        'name' => 'جنسنگ ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۳۰عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '1380',
        'retail_price' => '50',
    ],
    [
        'code' => 185,
        'name' => 'چاکلیت لالای ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کارتن',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1650',
        'retail_price' => '150',
    ],
    [
        'code' => 186,
        'name' => 'قندسفید ایرانی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۵کلیو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '380',
        'retail_price' => '100',
    ],
    [
        'code' => 187,
        'name' => 'سوپ ایلیت ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '360',
        'retail_price' => '30',
    ],
    [
        'code' => 188,
        'name' => 'آرد سوپ ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۰کیلو',
        'smallest_unit' => 'کلیو ',
        'size' => 'کلیو',
        'wholesale_price' => '1100',
        'retail_price' => '80',
    ],
    [
        'code' => 189,
        'name' => 'چاکلیت آناتا ۸۰۰گرام ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '950',
        'retail_price' => '170',
    ],
    [
        'code' => 190,
        'name' => 'چاکلیت ملک استار',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '1250',
        'retail_price' => '120',
    ],
    [
        'code' => 191,
        'name' => 'چاکلیت ایدین نارگیل',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '1750',
        'retail_price' => '160',
    ],
    [
        'code' => 192,
        'name' => 'چاکلیت آردین ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '1250',
        'retail_price' => '130',
    ],
    [
        'code' => 193,
        'name' => 'روب خورد تایماز ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد‍',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '1000',
        'retail_price' => '45',
    ],
    [
        'code' => 194,
        'name' => 'روب کلان تایماز ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '870',
        'retail_price' => '80',
    ],
    [
        'code' => 195,
        'name' => 'روب خورد طبعیت',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '950',
        'retail_price' => '40',
    ],
    [
        'code' => 196,
        'name' => 'روب کلان فریال ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '850',
        'retail_price' => '80',
    ],
    [
        'code' => 197,
        'name' => 'آش رشته تجلیل',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '750',
        'retail_price' => '40',
    ],
    [
        'code' => 198,
        'name' => 'وایتکس صحت',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '450',
        'retail_price' => '50',
    ],
    [
        'code' => 199,
        'name' => 'شیرینی ساده ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۷ سیر ',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '400',
        'retail_price' => '70',
    ],
    [
        'code' => 200,
        'name' => 'شیرنی جوار دار غلام سرور',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۷سیر',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '430',
        'retail_price' => '70',
    ],
    [
        'code' => 201,
        'name' => 'نقل بادامی ',
        'packing' => 'سیر ',
        'packaging_quantity' => '۷کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '650',
        'retail_price' => '80',
    ],
    [
        'code' => 202,
        'name' => 'نقل نخودی ',
        'packing' => 'سیر',
        'packaging_quantity' => '۷کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '550',
        'retail_price' => '70',
    ],
    [
        'code' => 203,
        'name' => 'پارتی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '340',
        'retail_price' => '20',
    ],
    [
        'code' => 204,
        'name' => 'دوایی دیگ مرحبا',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۶بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1300',
        'retail_price' => '100',
    ],
    [
        'code' => 205,
        'name' => 'مساله قابلی ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '480',
        'retail_price' => '50',
    ],
    [
        'code' => 206,
        'name' => 'مساله بریانی نشنل ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '450',
        'retail_price' => '50',
    ],
    [
        'code' => 207,
        'name' => 'مساله پلو نشنل ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '450',
        'retail_price' => '50',
    ],
    [
        'code' => 208,
        'name' => 'مساله قورمه نشنل',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '450',
        'retail_price' => '50',
    ],
    [
        'code' => 209,
        'name' => 'مساله کباب نشنل ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '450',
        'retail_price' => '50',
    ],
    [
        'code' => 210,
        'name' => 'هیل چایی بوتل ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۰ بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '820',
        'retail_price' => '100',
    ],
    [
        'code' => 211,
        'name' => 'هیل چایی کیلوی',
        'packing' => 'کیلو',
        'packaging_quantity' => '۱۰ خورد',
        'smallest_unit' => 'خورد',
        'size' => 'خورد',
        'wholesale_price' => '3300',
        'retail_price' => '340',
    ],
    [
        'code' => 212,
        'name' => 'خمرمایه کلان ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '2000',
        'retail_price' => '100',
    ],
    [
        'code' => 213,
        'name' => 'خمرمایه خورد ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۴۰پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '750',
        'retail_price' => '20',
    ],
    [
        'code' => 214,
        'name' => 'ریکاصحت',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '850',
        'retail_price' => '80',
    ],
    [
        'code' => 215,
        'name' => 'ریکا پریل ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۵بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1480',
        'retail_price' => '100',
    ],
    [
        'code' => 216,
        'name' => 'ریکا وهاب ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1160',
        'retail_price' => '160',
    ],
    [
        'code' => 217,
        'name' => 'ریکا ناب ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1040',
        'retail_price' => '150',
    ],
    [
        'code' => 218,
        'name' => 'پودر وهاب ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۰کلیو',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '960',
        'retail_price' => '100',
    ],
    [
        'code' => 219,
        'name' => 'پودر دران ',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۰کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '350',
        'retail_price' => '40',
    ],
    [
        'code' => 220,
        'name' => 'پودر گلشن',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۱۰کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '620',
        'retail_price' => '70',
    ],
    [
        'code' => 221,
        'name' => 'چاکلیت دارسا ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '950',
        'retail_price' => '100',
    ],
    [
        'code' => 222,
        'name' => 'ککو خوش قسمت',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸قطی',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '680',
        'retail_price' => '90',
    ],
    [
        'code' => 223,
        'name' => 'شامپو ناب ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '950',
        'retail_price' => '100',
    ],
    [
        'code' => 224,
        'name' => 'آتش زا ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '620',
        'retail_price' => '60',
    ],
    [
        'code' => 225,
        'name' => 'سرکه ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '420',
        'retail_price' => '50',
    ],
    [
        'code' => 226,
        'name' => 'ریکا گلرنگ ۸۰۰ سی سی',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '900',
        'retail_price' => '90',
    ],
    [
        'code' => 227,
        'name' => 'چاکلیت سهند ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '400',
        'retail_price' => '50',
    ],
    [
        'code' => 228,
        'name' => 'تار و مار ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲بوتل',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1050',
        'retail_price' => '100',
    ],
    [
        'code' => 229,
        'name' => 'آش مگی ترکی ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۸ بسته',
        'smallest_unit' => 'بسته ',
        'size' => 'پاکت',
        'wholesale_price' => '820',
        'retail_price' => '120',
    ],
    [
        'code' => 230,
        'name' => 'کرباو ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '1150',
        'retail_price' => '50',
    ],
    [
        'code' => 231,
        'name' => 'بسکویت گل گندم ۳۲عدد',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳۲دانه',
        'smallest_unit' => 'دانه',
        'size' => 'دانه ',
        'wholesale_price' => '480',
        'retail_price' => '20',
    ],
    [
        'code' => 232,
        'name' => 'بسکویت گل گندم ۳۶عدد',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۳۶ عدد',
        'smallest_unit' => 'دانه',
        'size' => 'دانه ',
        'wholesale_price' => '280',
        'retail_price' => '10',
    ],
    [
        'code' => 233,
        'name' => 'بسکویت دارسا ۶۰عدد',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶۰عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '180',
        'retail_price' => '5',
    ],
    [
        'code' => 234,
        'name' => 'لوبیا خرم ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '960',
        'retail_price' => '50',
    ],
    [
        'code' => 235,
        'name' => 'تن ماهی جسارت ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '1540',
        'retail_price' => '70',
    ],
    [
        'code' => 236,
        'name' => 'تن ماهی شاکر ۱۷۰گرام',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '1340',
        'retail_price' => '60',
    ],
    [
        'code' => 237,
        'name' => 'تن ماهی شاکر۱۴۰گرام ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '1140',
        'retail_price' => '50',
    ],
    [
        'code' => 238,
        'name' => 'تن ماهی شاکر ۱۲۰گرام',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '900',
        'retail_price' => '40',
    ],
    [
        'code' => 239,
        'name' => 'تن ماهی چانچو',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '2300',
        'retail_price' => '100',
    ],
    [
        'code' => 240,
        'name' => 'هیت جنسنگ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '590',
        'retail_price' => '30',
    ],
    [
        'code' => 241,
        'name' => 'اکسبول جسنگ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۲۴بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '560',
        'retail_price' => '30',
    ],
    [
        'code' => 242,
        'name' => 'شیر یک لیتر پگاه',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۰ پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '740',
        'retail_price' => '80',
    ],
    [
        'code' => 243,
        'name' => 'شیر ۱لیتر آل ملک',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '720',
        'retail_price' => '70',
    ],
    [
        'code' => 244,
        'name' => 'کشک ایرانی ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۱۲ بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '850',
        'retail_price' => '70',
    ],
    [
        'code' => 245,
        'name' => 'مربا کلان طبعیت',
        'packing' => 'بسته ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '650',
        'retail_price' => '120',
    ],
    [
        'code' => 246,
        'name' => 'قهوه پاکت',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۲پاکت',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '',
        'retail_price' => '220',
    ],
    [
        'code' => 247,
        'name' => 'عسل استرالیا ۱۰۰۰گرام',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '2100',
        'retail_price' => '450',
    ],
    [
        'code' => 248,
        'name' => 'عسل استرالیا۲۰۰۰گرام',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل ',
        'size' => 'بوتل',
        'wholesale_price' => '3200',
        'retail_price' => '550',
    ],
    [
        'code' => 249,
        'name' => 'عسل کندو بال ',
        'packing' => 'بسته ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '450',
        'retail_price' => '90',
    ],
    [
        'code' => 250,
        'name' => 'کیچیب ۳لیتر ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بوتل ',
        'smallest_unit' => 'بوتل',
        'size' => 'بوتل',
        'wholesale_price' => '550',
        'retail_price' => '90',
    ],
    [
        'code' => 251,
        'name' => 'روغن مو وازلین ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '540',
        'retail_price' => '60',
    ],
    [
        'code' => 252,
        'name' => 'پل ریش دارکو ۱۰عدد',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۶بسته ',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '560',
        'retail_price' => '30',
    ],
    [
        'code' => 253,
        'name' => 'پل ریش دارکو ۵عدد',
        'packing' => 'تخته',
        'packaging_quantity' => '۴۰عدد',
        'smallest_unit' => 'عدد',
        'size' => 'عدد',
        'wholesale_price' => '320',
        'retail_price' => '10',
    ],
    [
        'code' => 254,
        'name' => 'ژیلیت پیچ بن',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۶قطی',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '6720',
        'retail_price' => '440',
    ],
    [
        'code' => 255,
        'name' => 'ژیلیت صابون دار دارکو',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۱۶قطی',
        'smallest_unit' => 'پاکت',
        'size' => 'پاکت',
        'wholesale_price' => '8960',
        'retail_price' => '560',
    ],
    [
        'code' => 256,
        'name' => 'فندک ساده ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۰بسته',
        'smallest_unit' => 'دانه ',
        'size' => 'دانه',
        'wholesale_price' => '5000',
        'retail_price' => '250',
    ],
    [
        'code' => 257,
        'name' => 'کرم سه برگ',
        'packing' => 'کارتن ',
        'packaging_quantity' => '۲۴درجن',
        'smallest_unit' => 'دانه ',
        'size' => 'دانه ',
        'wholesale_price' => '4320',
        'retail_price' => '180',
    ],
    [
        'code' => 258,
        'name' => 'زعفران ۲۰۰گرام ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '2380',
        'retail_price' => '220',
    ],
    [
        'code' => 259,
        'name' => 'رعفران ۱۰۰گرام ',
        'packing' => 'درجن',
        'packaging_quantity' => '۱۲قطی ',
        'smallest_unit' => 'قطی',
        'size' => 'قطی',
        'wholesale_price' => '1680',
        'retail_price' => '150',
    ],
    [
        'code' => 260,
        'name' => 'پلاستیک',
        'packing' => 'بوجی ',
        'packaging_quantity' => '۲۵کیلو',
        'smallest_unit' => 'کیلو',
        'size' => 'کیلو',
        'wholesale_price' => '2750',
        'retail_price' => '110',
    ],
];

        DB::table('items')->insert($items);
    }
}
