<?php

namespace Database\Seeders\Administration;

use App\Models\Administration\Currency;
use Illuminate\Database\Seeder;
use App\Models\Administration\Branch;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branch = Branch::where('is_main', true)->first();
        $currencyList = [
            // Most important currencies first
            'AFN' => [
                'name' => 'Afghanistan, Afghani',
                'symbol' => '؋',
                'format' => '؋1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'af.png',
                'is_active' => true,
                'is_base_currency' => true,
                'branch_id' => $branch->id,
            ],
            'USD' => [
                'name' => 'US Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'us.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'IRR' => [
                'name' => 'Iranian Rial',
                'symbol' => '﷼',
                'format' => '﷼ 1,0/00',
                'exchange_rate' => 0.00,
                'flag'     => 'ir.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'INR' => [
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'format' => '1,0.00₹',
                'exchange_rate' => 0.00,
                'flag'     => 'in.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'AED' => [
                'name' => 'UAE Dirham',
                'symbol' => 'دإ‏',
                'format' => 'دإ‏ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ae.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ALL' => [
                'name' => 'Albania, Lek',
                'symbol' => 'Lek',
                'format' => '1,0.00Lek',
                'exchange_rate' => 0.00,
                'flag'     => 'al.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'AMD' => [
                'name' => 'Armenian Dram',
                'symbol' => '&#1423;',
                'format' => '1,0.00 &#1423;',
                'exchange_rate' => 0.00,
                'flag'     => 'am.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ANG' => [
                'name' => 'Netherlands Antillian Guilder',
                'symbol' => 'ƒ',
                'format' => 'ƒ1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'an.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'AOA' => [
                'name' => 'Angola, Kwanza',
                'symbol' => 'Kz',
                'format' => 'Kz1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ao.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ARS' => [
                'name' => 'Argentine Peso',
                'symbol' => '$',
                'format' => '$ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ar.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'AUD' => [
                'name' => 'Australian Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'au.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'AWG' => [
                'name' => 'Aruban Guilder',
                'symbol' => 'ƒ',
                'format' => 'ƒ1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'aw.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'AZN' => [
                'name' => 'Azerbaijanian Manat',
                'symbol' => '₼',
                'format' => '1 0,00 ₼',
                'exchange_rate' => 0.00,
                'flag'     => 'az.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BAM' => [
                'name' => 'Bosnia and Herzegovina, Convertible Marks',
                'symbol' => 'КМ',
                'format' => '1,0.00 КМ',
                'exchange_rate' => 0.00,
                'flag'     => 'ba.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BBD' => [
                'name' => 'Barbados Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'bb.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BDT' => [
                'name' => 'Bangladesh, Taka',
                'symbol' => '৳',
                'format' => '৳ 1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'bd.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BGN' => [
                'name' => 'Bulgarian Lev',
                'symbol' => 'лв.',
                'format' => '1 0,00 лв.',
                'exchange_rate' => 0.00,
                'flag'     => 'bg.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BHD' => [
                'name' => 'Bahraini Dinar',
                'symbol' => '.د.',
                'format' => '.د. 1,0.000',
                'exchange_rate' => 0.00,
                'flag'     => 'bh.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BIF' => [
                'name' => 'Burundi Franc',
                'symbol' => 'FBu',
                'format' => '1,0.FBu',
                'exchange_rate' => 0.00,
                'flag'     => 'bi.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BMD' => [
                'name' => 'Bermudian Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'bm.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BND' => [
                'name' => 'Brunei Dollar',
                'symbol' => '$',
                'format' => '$1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'bn.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BOB' => [
                'name' => 'Bolivia, Boliviano',
                'symbol' => 'Bs',
                'format' => 'Bs 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'bo.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BRL' => [
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'format' => 'R$ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'br.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BSD' => [
                'name' => 'Bahamian Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'bs.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BTN' => [
                'name' => 'Bhutan, Ngultrum',
                'symbol' => 'Nu.',
                'format' => 'Nu. 1,0.0',
                'exchange_rate' => 0.00,
                'flag'     => 'bt.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BWP' => [
                'name' => 'Botswana, Pula',
                'symbol' => 'P',
                'format' => 'P1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'bw.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BYR' => [
                'name' => 'Belarussian Ruble',
                'symbol' => 'р.',
                'format' => '1 0,00 р.',
                'exchange_rate' => 0.00,
                'flag'     => 'by.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'BZD' => [
                'name' => 'Belize Dollar',
                'symbol' => 'BZ$',
                'format' => 'BZ$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'bz.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CAD' => [
                'name' => 'Canadian Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'can.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CDF' => [
                'name' => 'Franc Congolais',
                'symbol' => 'FC',
                'format' => '1,0.00FC',
                'exchange_rate' => 0.00,
                'flag'     => 'cd.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CHF' => [
                'name' => 'Swiss Franc',
                'symbol' => 'CHF',
                'format' => '1\'0.00 CHF',
                'exchange_rate' => 0.00,
                'flag'     => 'ca.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CLP' => [
                'name' => 'Chilean Peso',
                'symbol' => '$',
                'format' => '$ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'cl.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CNY' => [
                'name' => 'China Yuan Renminbi',
                'symbol' => '¥',
                'format' => '¥1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'cn.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'COP' => [
                'name' => 'Colombian Peso',
                'symbol' => '$',
                'format' => '$ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'co.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CRC' => [
                'name' => 'Costa Rican Colon',
                'symbol' => '₡',
                'format' => '₡1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'cr.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CUC' => [
                'name' => 'Cuban Convertible Peso',
                'symbol' => 'CUC',
                'format' => 'CUC1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'cc.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CUP' => [
                'name' => 'Cuban Peso',
                'symbol' => '$MN',
                'format' => '$MN1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'cu.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CVE' => [
                'name' => 'Cape Verde Escudo',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'cv.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'CZK' => [
                'name' => 'Czech Koruna',
                'symbol' => 'Kč',
                'format' => '1 0,00 Kč',
                'exchange_rate' => 0.00,
                'flag'     => 'cz.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'DJF' => [
                'name' => 'Djibouti Franc',
                'symbol' => 'Fdj',
                'format' => '1,0.Fdj',
                'exchange_rate' => 0.00,
                'flag'     => 'dj.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'DKK' => [
                'name' => 'Danish Krone',
                'symbol' => 'kr.',
                'format' => '1 0,00 kr.',
                'exchange_rate' => 0.00,
                'flag'     => 'dk.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'DOP' => [
                'name' => 'Dominican Peso',
                'symbol' => 'RD$',
                'format' => 'RD$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'do.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'DZD' => [
                'name' => 'Algerian Dinar',
                'symbol' => 'د.ج‏',
                'format' => 'د.ج‏ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'dz.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'EGP' => [
                'name' => 'Egyptian Pound',
                'symbol' => 'ج.م',
                'format' => 'ج.م 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'eg.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ERN' => [
                'name' => 'Eritrea, Nakfa',
                'symbol' => 'Nfk',
                'format' => '1,0.00Nfk',
                'exchange_rate' => 0.00,
                'flag'     => 'er.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ETB' => [
                'name' => 'Ethiopian Birr',
                'symbol' => 'ETB',
                'format' => 'ETB1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'et.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'EUR' => [
                'name' => 'Euro',
                'symbol' => '€',
                'format' => '1.0,00 €',
                'exchange_rate' => 0.00,
                'flag'     => 'eu.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'FJD' => [
                'name' => 'Fiji Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ej.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'FKP' => [
                'name' => 'Falkland Islands Pound',
                'symbol' => '£',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'fk.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GBP' => [
                'name' => 'Pound Sterling',
                'symbol' => '£',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'gb.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GEL' => [
                'name' => 'Georgia, Lari',
                'symbol' => 'Lari',
                'format' => '1 0,00 Lari',
                'exchange_rate' => 0.00,
                'flag'     => 'ge.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GHS' => [
                'name' => 'Ghana Cedi',
                'symbol' => '₵',
                'format' => '₵1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'gh.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GIP' => [
                'name' => 'Gibraltar Pound',
                'symbol' => '£',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'gi.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GMD' => [
                'name' => 'Gambia, Dalasi',
                'symbol' => 'D',
                'format' => '1,0.00D',
                'exchange_rate' => 0.00,
                'flag'     => 'gm.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GTQ' => [
                'name' => 'Guatemala, Quetzal',
                'symbol' => 'Q',
                'format' => 'Q1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'gt.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'GYD' => [
                'name' => 'Guyana Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'gy.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'HKD' => [
                'name' => 'Hong Kong Dollar',
                'symbol' => 'HK$',
                'format' => 'HK$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'hk.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'HNL' => [
                'name' => 'Honduras, Lempira',
                'symbol' => 'L.',
                'format' => 'L. 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'hn.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'HRK' => [
                'name' => 'Croatian Kuna',
                'symbol' => 'kn',
                'format' => '1,0.00 kn',
                'exchange_rate' => 0.00,
                'flag'     => 'hr.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'HTG' => [
                'name' => 'Haiti, Gourde',
                'symbol' => 'G',
                'format' => 'G1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ht.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'HUF' => [
                'name' => 'Hungary, Forint',
                'symbol' => 'Ft',
                'format' => '1 0,00 Ft',
                'exchange_rate' => 0.00,
                'flag'     => 'hu.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'IDR' => [
                'name' => 'Indonesia, Rupiah',
                'symbol' => 'Rp',
                'format' => 'Rp1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'id.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ILS' => [
                'name' => 'New Israeli Shekel',
                'symbol' => '₪',
                'format' => '₪ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'il.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'INR' => [
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'format' => '1,0.00₹',
                'exchange_rate' => 0.00,
                'flag'     => 'in.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'IQD' => [
                'name' => 'Iraqi Dinar',
                'symbol' => 'د.ع.‏',
                'format' => 'د.ع.‏ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'iq.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'ISK' => [
                'name' => 'Iceland Krona',
                'symbol' => 'kr.',
                'format' => '1,0. kr.',
                'exchange_rate' => 0.00,
                'flag'     => 'is.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'JMD' => [
                'name' => 'Jamaican Dollar',
                'symbol' => 'J$',
                'format' => 'J$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'jm.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'JOD' => [
                'name' => 'Jordanian Dinar',
                'symbol' => 'د.ا.‏',
                'format' => 'د.ا.‏ 1,0.000',
                'exchange_rate' => 0.00,
                'flag'     => 'jo.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'JPY' => [
                'name' => 'Japan, Yen',
                'symbol' => '¥',
                'format' => '¥1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'jp.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KES' => [
                'name' => 'Kenyan Shilling',
                'symbol' => 'S',
                'format' => 'S1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ke.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KGS' => [
                'name' => 'Kyrgyzstan, Som',
                'symbol' => 'сом',
                'format' => '1 0-00 сом',
                'exchange_rate' => 0.00,
                'flag'     => 'kg.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KHR' => [
                'name' => 'Cambodia, Riel',
                'symbol' => '៛',
                'format' => '1,0.៛',
                'exchange_rate' => 0.00,
                'flag'     => 'kh.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KMF' => [
                'name' => 'Comoro Franc',
                'symbol' => 'CF',
                'format' => '1,0.00CF',
                'exchange_rate' => 0.00,
                'flag'     => 'km.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KPW' => [
                'name' => 'North Korean Won',
                'symbol' => '₩',
                'format' => '₩1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'kp.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KRW' => [
                'name' => 'South Korea, Won',
                'symbol' => '₩',
                'format' => '₩1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'kr.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KWD' => [
                'name' => 'Kuwaiti Dinar',
                'symbol' => 'دينار‌‌‏',
                'format' => 'دينار‌‌‏ 1,0.000',
                'exchange_rate' => 0.00,
                'flag'     => 'kw.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KYD' => [
                'name' => 'Cayman Islands Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'ky.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'KZT' => [
                'name' => 'Kazakhstan, Tenge',
                'symbol' => '₸',
                'format' => '₸1 0-00',
                'exchange_rate' => 0.00,
                'flag'     => 'kz.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'LAK' => [
                'name' => 'Laos, Kip',
                'symbol' => '₭',
                'format' => '1,0.₭',
                'exchange_rate' => 0.00,
                'flag'     => 'la.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'LBP' => [
                'name' => 'Lebanese Pound',
                'symbol' => 'ل.ل.‏',
                'format' => 'ل.ل.‏ 1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'lb.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'LKR' => [
                'name' => 'Sri Lanka Rupee',
                'symbol' => '₨',
                'format' => '₨ 1,0.',
                'exchange_rate' => 0.00,
                'flag'     => 'lk.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'LRD' => [
                'name' => 'Liberian Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag'     => 'lr.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'LSL' => [
                'name' => 'Lesotho, Loti',
                'symbol' => 'M',
                'format' => '1,0.00M',
                'exchange_rate' => 0.00,
                'flag' => 'ls.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'LYD' => [
                'name' => 'Libyan Dinar',
                'symbol' => 'د.ل.‏',
                'format' => 'د.ل.‏1,0.000',
                'exchange_rate' => 0.00,
                'flag' => 'ly.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MAD' => [
                'name' => 'Moroccan Dirham',
                'symbol' => 'د.م.‏',
                'format' => 'د.م.‏ 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'ma.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MDL' => [
                'name' => 'Moldovan Leu',
                'symbol' => 'lei',
                'format' => '1,0.00 lei',
                'exchange_rate' => 0.00,
                'flag' => 'md.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MGA' => [
                'name' => 'Malagasy Ariary',
                'symbol' => 'Ar',
                'format' => 'Ar1,0.',
                'exchange_rate' => 0.00,
                'flag' => 'mg.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MKD' => [
                'name' => 'Macedonia, Denar',
                'symbol' => 'ден.',
                'format' => '1,0.00 ден.',
                'exchange_rate' => 0.00,
                'flag' => 'mk.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MMK' => [
                'name' => 'Myanmar, Kyat',
                'symbol' => 'K',
                'format' => 'K1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'mm.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MNT' => [
                'name' => 'Mongolia, Tugrik',
                'symbol' => '₮',
                'format' => '₮1 0,00',
                'exchange_rate' => 0.00,
                'flag' => 'mn.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MOP' => [
                'name' => 'Macao, Pataca',
                'symbol' => 'MOP$',
                'format' => 'MOP$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'mo.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MRO' => [
                'name' => 'Mauritania, Ouguiya',
                'symbol' => 'UM',
                'format' => '1,0.00UM',
                'exchange_rate' => 0.00,
                'flag' => 'mr.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MTL' => [
                'name' => 'Maltese Lira',
                'symbol' => '₤',
                'format' => '₤1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'mt.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MUR' => [
                'name' => 'Mauritius Rupee',
                'symbol' => '₨',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'mu.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MVR' => [
                'name' => 'Maldives, Rufiyaa',
                'symbol' => 'MVR',
                'format' => '1,0.0 MVR',
                'exchange_rate' => 0.00,
                'flag' => 'mv.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MWK' => [
                'name' => 'Malawi, Kwacha',
                'symbol' => 'MK',
                'format' => 'MK1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'mw.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MXN' => [
                'name' => 'Mexican Peso',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'mx.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MYR' => [
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'format' => 'RM1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'my.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'MZN' => [
                'name' => 'Mozambique Metical',
                'symbol' => 'MT',
                'format' => 'MT1,0.',
                'exchange_rate' => 0.00,
                'flag' => 'mz.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'NAD' => [
                'name' => 'Namibian Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'na.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'NGN' => [
                'name' => 'Nigeria, Naira',
                'symbol' => '₦',
                'format' => '₦1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'nn.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'NIO' => [
                'name' => 'Nicaragua, Cordoba Oro',
                'symbol' => 'C$',
                'format' => 'C$ 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'ni.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'NOK' => [
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'format' => '1.0,00 kr',
                'exchange_rate' => 0.00,
                'flag' => 'no.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'NPR' => [
                'name' => 'Nepalese Rupee',
                'symbol' => '₨',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'np.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'NZD' => [
                'name' => 'New Zealand Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'nz.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'OMR' => [
                'name' => 'Rial Omani',
                'symbol' => '﷼',
                'format' => '﷼ 1,0.000',
                'exchange_rate' => 0.00,
                'flag' => 'om.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'PAB' => [
                'name' => 'Panama, Balboa',
                'symbol' => 'B/.',
                'format' => 'B/. 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'pa.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'PEN' => [
                'name' => 'Peru, Nuevo Sol',
                'symbol' => 'S/.',
                'format' => 'S/. 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'pe.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'PGK' => [
                'name' => 'Papua New Guinea, Kina',
                'symbol' => 'K',
                'format' => 'K1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'pg.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'PHP' => [
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'format' => '₱1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'ph.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'PLN' => [
                'name' => 'Poland, Zloty',
                'symbol' => 'zł',
                'format' => '1 0,00 zł',
                'exchange_rate' => 0.00,
                'flag' => 'pl.png',
                'is_active' => true,
                'branch_id' => $branch->id,
            ],
            'PYG' => [
                'name' => 'Paraguay, Guarani',
                'symbol' => '₲',
                'format' => '₲ 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'py.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'QAR' => [
                'name' => 'Qatari Rial',
                'symbol' => '﷼',
                'format' => '﷼ 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'qa.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'RON' => [
                'name' => 'Romania, New Leu',
                'symbol' => 'lei',
                'format' => '1,0.00 lei',
                'exchange_rate' => 0.00,
                'flag' => 'ro.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'RSD' => [
                'name' => 'Serbian Dinar',
                'symbol' => 'Дин.',
                'format' => '1,0.00 Дин.',
                'exchange_rate' => 0.00,
                'flag' => 'rs.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'RUB' => [
                'name' => 'Russian Ruble',
                'symbol' => '₽',
                'format' => '1 0,00 ₽',
                'exchange_rate' => 0.00,
                'flag' => 'ru.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'RWF' => [
                'name' => 'Rwanda Franc',
                'symbol' => 'RWF',
                'format' => 'RWF 1 0,00',
                'exchange_rate' => 0.00,
                'flag' => 'rw.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SAR' => [
                'name' => 'Saudi Riyal',
                'symbol' => '﷼',
                'format' => '﷼ 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sa.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SBD' => [
                'name' => 'Solomon Islands Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sb.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SCR' => [
                'name' => 'Seychelles Rupee',
                'symbol' => '₨',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sc.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SDD' => [
                'name' => 'Sudanese Dinar',
                'symbol' => 'LSd',
                'format' => '1,0.00LSd',
                'exchange_rate' => 0.00,
                'flag' => 'sd.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SEK' => [
                'name' => 'Swedish Krona',
                'symbol' => 'kr',
                'format' => '1 0,00 kr',
                'exchange_rate' => 0.00,
                'flag' => 'se.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SGD' => [
                'name' => 'Singapore Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sg.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SHP' => [
                'name' => 'Saint Helena Pound',
                'symbol' => '£',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sh.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SLL' => [
                'name' => 'Sierra Leone, Leone',
                'symbol' => 'Le',
                'format' => 'Le1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sl.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SOS' => [
                'name' => 'Somali Shilling',
                'symbol' => 'S',
                'format' => 'S1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'so.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SRD' => [
                'name' => 'Surinam Dollar',
                'symbol' => '$',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sr.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'STD' => [
                'name' => 'Sao Tome and Principe, Dobra',
                'symbol' => 'Db',
                'format' => 'Db1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'st.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SVC' => [
                'name' => 'El Salvador Colon',
                'symbol' => '₡',
                'format' => '₡1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sv.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SYP' => [
                'name' => 'Syrian Pound',
                'symbol' => '£',
                'format' => '£ 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sy.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'SZL' => [
                'name' => 'Swaziland, Lilangeni',
                'symbol' => 'E',
                'format' => 'E1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'sz.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'THB' => [
                'name' => 'Thailand, Baht',
                'symbol' => '฿',
                'format' => '฿1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'th.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TJS' => [
                'name' => 'Tajikistan, Somoni',
                'symbol' => 'TJS',
                'format' => '1 0;00 TJS',
                'exchange_rate' => 0.00,
                'flag' => 'tj.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TMT' => [
                'name' => 'Turkmenistani New Manat',
                'symbol' => 'm',
                'format' => '1 0,m',
                'exchange_rate' => 0.00,
                'flag' => 'tm.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TND' => [
                'name' => 'Tunisian Dinar',
                'symbol' => 'د.ت.‏',
                'format' => 'د.ت.‏ 1,0.000',
                'exchange_rate' => 0.00,
                'flag' => 'tn.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TOP' => [
                'name' => 'Tonga, Paanga',
                'symbol' => 'T$',
                'format' => 'T$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'to.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TRY' => [
                'name' => 'Turkish Lira',
                'symbol' => 'TL',
                'format' => '₺1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'tr.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TTD' => [
                'name' => 'Trinidad and Tobago Dollar',
                'symbol' => 'TT$',
                'format' => 'TT$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'tt.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TWD' => [
                'name' => 'New Taiwan Dollar',
                'symbol' => 'NT$',
                'format' => 'NT$1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'tw.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'TZS' => [
                'name' => 'Tanzanian Shilling',
                'symbol' => 'TSh',
                'format' => 'TSh1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'tz.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'UAH' => [
                'name' => 'Ukraine, Hryvnia',
                'symbol' => '₴',
                'format' => '1 0,00₴',
                'exchange_rate' => 0.00,
                'flag' => 'ua.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
            'UGX' => [
                'name' => 'Uganda Shilling',
                'symbol' => 'USh',
                'format' => 'USh1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'ug.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],

            'UYU' => [
                'name' => 'Peso Uruguayo',
                'symbol' => '$U',
                'format' => '$U 1,0.00',
                'exchange_rate' => 0.00,
                'flag' => 'uy.png',
                'branch_id' => $branch->id,
                'is_active' => true,
            ],
        ];
        foreach ($currencyList as $key => $value) {
            $temp = $value + ['code' => $key];
            // Ensure is_base_currency is set for all currencies
            if (!isset($temp['is_base_currency'])) {
                $temp['is_base_currency'] = false;
            }
            Currency::create($temp);
        }
    }
}
