/**
 * i18n keys indexed per preferences tab for locale-aware search.
 * English tabSearchTerms in Index.vue are kept as a secondary fallback.
 */
export const PREFERENCE_TAB_I18N_KEYS = {
    appearance: [
        'preferences.tabs.appearance',
        'preferences.appearance.description',
        'preferences.appearance.font_size',
        'preferences.appearance.color_palette',
        'preferences.appearance.color_mode',
        'preferences.appearance.accent_color',
        'preferences.appearance.decimal_places',
        'preferences.appearance.balance_nature_format',
        'preferences.appearance.without_nature',
        'preferences.appearance.with_nature',
        'preferences.appearance.records_per_page',
        'preferences.appearance.sidebar_menus',
        'preferences.appearance.sidebar_font_size',
        'preferences.appearance.heading_font_size',
        'preferences.appearance.table_header_font_size',
        'preferences.appearance.table_content_font_size',
        'preferences.appearance.button_font_size',
        'preferences.appearance.label_font_size',
        'preferences.appearance.input_font_size',
        'preferences.appearance.select_font_size',
        'preferences.appearance.textarea_font_size',
        'preferences.appearance.light',
        'preferences.appearance.dark',
        'preferences.appearance.system',
        'preferences.appearance.red',
        'preferences.appearance.orange',
        'preferences.appearance.amber',
        'preferences.appearance.yellow',
        'preferences.appearance.lime',
        'preferences.appearance.green',
        'preferences.appearance.emerald',
        'preferences.appearance.teal',
        'preferences.appearance.cyan',
        'preferences.appearance.sky',
        'preferences.appearance.blue',
        'preferences.appearance.indigo',
        'preferences.appearance.violet',
        'preferences.appearance.purple',
        'preferences.appearance.fuchsia',
        'preferences.appearance.pink',
        'preferences.appearance.rose',
        'preferences.appearance.slate',
        'preferences.appearance.gray',
        'preferences.appearance.zinc',
        'preferences.appearance.neutral',
        'preferences.appearance.stone',
        'preferences.appearance.taupe',
        'preferences.appearance.mauve',
        'preferences.appearance.mist',
        'preferences.appearance.olive',
    ],
    item_management: [
        'preferences.tabs.item_management',
        'preferences.item_management.description',
        'preferences.item_management.visible_fields',
        'preferences.tax_currency.spec_text',
        'general.confirm_before_save',
        'preferences.transaction.confirm_before_save_help',
    ],
    stock_adjustment: [
        'preferences.tabs.stock_adjustment',
        'preferences.stock_adjustment.title',
        'preferences.stock_adjustment.description',
        'preferences.stock_adjustment.reference_prefix',
        'preferences.stock_adjustment.allow_in_cost_override',
        'preferences.stock_adjustment.reason_accounts',
        'preferences.stock_adjustment.reason_accounts_help',
        'preferences.stock_adjustment.accounts.shrinkage',
        'preferences.stock_adjustment.accounts.adjustments',
        'preferences.transaction.post_immediately',
        'general.confirm_before_save',
        'adjustment.reasons.damage',
        'adjustment.reasons.expiry',
        'adjustment.reasons.theft',
        'adjustment.reasons.loss',
        'adjustment.reasons.count_down',
        'adjustment.reasons.internal_use',
        'adjustment.reasons.sample',
        'adjustment.reasons.wastage',
        'adjustment.reasons.quality_rejection',
        'adjustment.reasons.count_up',
        'adjustment.reasons.found',
        'adjustment.reasons.opening_stock',
        'adjustment.reasons.production_output',
        'adjustment.reasons.surplus',
    ],
    sale: [
        'preferences.tabs.sale',
        'preferences.sale.description',
        'preferences.sale.general_fields',
        'preferences.sale.item_columns',
        'preferences.sale.invoice_prefix',
        'preferences.sale.start_number',
        'preferences.sale.due_days',
        'preferences.sale.terms',
        'preferences.sale.invoice_theme',
        'preferences.sale.invoice_theme_description',
        'preferences.sale.selected_theme',
        'preferences.sale.preview_hint',
        'preferences.sale.selected',
        'preferences.sale.preview',
        'preferences.sale.select_theme',
        'preferences.sale.current_theme',
        'preferences.sale.auto_reminders',
        'preferences.sale.reminder_days',
        'preferences.sale.late_fee_percentage',
        'preferences.sale.tax_percentage',
        'preferences.sale.auto_calculate_tax',
        'preferences.sale.show_ledger_transactions',
        'preferences.sale.show_item_transactions',
        'preferences.sale.enforce_sale_stock_reservation',
        'preferences.sale.enforce_sale_stock_reservation_help',
        'preferences.sale.types.sale',
        'preferences.sale.types.sale_order',
        'preferences.sale.types.sale_return',
        'preferences.sale.types.sale_quotation',
        'general.confirm_before_save',
        'preferences.transaction.confirm_before_save_help',
    ],
    purchase: [
        'preferences.tabs.purchase',
        'preferences.purchase.description',
        'preferences.purchase.general_fields',
        'preferences.purchase.item_columns',
        'preferences.purchase.invoice_prefix',
        'preferences.purchase.start_number',
        'preferences.purchase.due_days',
        'preferences.purchase.terms',
        'preferences.purchase.auto_reminders',
        'preferences.purchase.reminder_days',
        'preferences.purchase.late_fee_percentage',
        'preferences.purchase.show_ledger_transactions',
        'preferences.purchase.show_item_transactions',
        'preferences.purchase.types.purchase',
        'preferences.purchase.types.purchase_order',
        'preferences.purchase.types.purchase_return',
        'preferences.purchase.types.purchase_quotation',
        'general.confirm_before_save',
        'preferences.transaction.confirm_before_save_help',
    ],
    receipt_payment: [
        'preferences.tabs.receipt_payment',
        'preferences.receipt_payment.description',
        'preferences.receipt_payment.visible_fields',
        'preferences.receipt_payment.default_cash_account',
        'preferences.receipt_payment.select_account',
        'preferences.receipt_payment.lock_after_days',
        'preferences.receipt_payment.auto_sequence',
        'preferences.receipt_payment.require_approval',
        'preferences.transaction.modules.receipt',
        'preferences.transaction.modules.payment',
        'general.confirm_before_save',
    ],
    transaction: [
        'preferences.tabs.transaction',
        'preferences.transaction.description',
        'preferences.transaction.post_immediately',
        'preferences.transaction.post_immediately_help',
        'preferences.transaction.confirm_before_save_help',
        'general.confirm_before_save',
        'preferences.transaction.modules.sale',
        'preferences.transaction.modules.purchase',
        'preferences.transaction.modules.expense',
        'preferences.transaction.modules.journal_entry',
        'preferences.transaction.modules.receipt',
        'preferences.transaction.modules.payment',
        'preferences.transaction.modules.account_transfer',
        'preferences.transaction.modules.item_transfer',
        'preferences.transaction.modules.drawing',
        'preferences.transaction.modules.ledger',
        'preferences.transaction.modules.account',
        'preferences.transaction.modules.owner',
    ],
    tax_currency: [
        'preferences.tabs.tax_currency',
        'preferences.tax_currency.description',
        'preferences.tax_currency.tax_plus',
        'preferences.tax_currency.tax_minus',
        'preferences.tax_currency.multi_currency_opening',
    ],
    notifications: [
        'preferences.tabs.notifications',
        'preferences.notifications.description',
        'preferences.notifications.email_notifications',
        'preferences.notifications.email_notifications_desc',
        'preferences.notifications.low_balance_alert',
        'preferences.notifications.low_balance_alert_desc',
        'preferences.notifications.low_item_balance_alert',
        'preferences.notifications.low_item_balance_alert_desc',
        'preferences.notifications.nearest_expiry_alert',
        'preferences.notifications.nearest_expiry_alert_desc',
        'preferences.notifications.overdue_purchase_alert',
        'preferences.notifications.overdue_purchase_alert_desc',
        'preferences.notifications.overdue_sale_alert',
        'preferences.notifications.overdue_sale_alert_desc',
        'preferences.notifications.overdue_invoice_alert',
        'preferences.notifications.overdue_invoice_alert_desc',
        'preferences.notifications.sale_paid_alert',
        'preferences.notifications.sale_paid_alert_desc',
        'preferences.notifications.purchase_paid_alert',
        'preferences.notifications.purchase_paid_alert_desc',
        'preferences.notifications.new_transaction_alert',
        'preferences.notifications.new_transaction_alert_desc',
        'preferences.notifications.daily_summary_report',
        'preferences.notifications.daily_summary_report_desc',
        'preferences.notifications.weekly_financial_summary',
        'preferences.notifications.weekly_financial_summary_desc',
    ],
    security: [
        'preferences.tabs.security',
        'preferences.security.description',
        'preferences.security.session_timeout',
        'preferences.security.session_timeout_hint',
        'preferences.security.login_attempts_limit',
        'preferences.security.password_min_length',
        'preferences.security.password_special_chars',
        'preferences.security.two_factor_auth',
        'preferences.security.report_lock',
        'preferences.security.lock_reports',
        'preferences.security.lock_password',
    ],
    install_plugins: [
        'preferences.tabs.install_plugins',
        'preferences.install_plugins.description',
        'preferences.install_plugins.save',
        'preferences.install_plugins.measures_title',
        'preferences.install_plugins.measures_hint',
        'preferences.install_plugins.warehouses_title',
        'preferences.install_plugins.warehouses_hint',
        'preferences.install_plugins.categories_title',
        'preferences.install_plugins.categories_hint',
        'preferences.install_plugins.sizes_title',
        'preferences.install_plugins.sizes_hint',
        'preferences.install_plugins.currencies_title',
        'preferences.install_plugins.currencies_hint',
        'preferences.install_plugins.ledgers_title',
        'preferences.install_plugins.ledgers_hint',
        'preferences.install_plugins.customers_title',
        'preferences.install_plugins.suppliers_title',
        'preferences.install_plugins.main_badge',
        'preferences.install_plugins.base_badge',
    ],
    backup: [
        'preferences.tabs.backup',
        'preferences.backup.description',
        'preferences.backup.auto_backup',
        'preferences.backup.none',
        'preferences.backup.daily',
        'preferences.backup.weekly',
        'preferences.backup.monthly',
        'preferences.backup.backup_retention_days',
        'preferences.backup.cloud_backup',
        'preferences.backup.cloud_provider',
        'preferences.backup.export_formats',
    ],
    localization: [
        'preferences.tabs.localization',
        'preferences.localization.description',
        'preferences.localization.language',
        'preferences.localization.timezone',
        'preferences.localization.date_format',
        'preferences.localization.time_format',
        'preferences.localization.number_format',
        'preferences.localization.first_day_of_week',
        'preferences.localization.sunday',
        'preferences.localization.monday',
        'preferences.localization.saturday',
    ],
    display: [
        'preferences.tabs.display',
        'preferences.display.description',
        'preferences.display.theme',
        'preferences.display.records_per_page',
        'preferences.display.dashboard_charts',
        'preferences.display.dashboard_charts_desc',
        'preferences.display.show_currency_symbol',
        'preferences.display.show_currency_symbol_desc',
        'preferences.display.compact_view',
        'preferences.display.compact_view_desc',
        'preferences.display.sidebar_collapsed',
        'preferences.display.sidebar_collapsed_desc',
        'preferences.appearance.light',
        'preferences.appearance.dark',
        'preferences.appearance.system',
    ],
    invoice_designer: [
        'preferences.tabs.invoice_designer',
        'preferences.invoice_designer.select_help',
        'preferences.invoice_designer.builtin_formats',
        'preferences.invoice_designer.custom_formats',
        'preferences.invoice_designer.new',
        'preferences.invoice_designer.empty',
        'preferences.invoice_designer.empty_hint',
        'preferences.invoice_designer.active',
        'preferences.invoice_designer.empty_state',
        'preferences.invoice_designer.empty_state_hint',
        'preferences.invoice_designer.create',
        'preferences.invoice_designer.format_name',
    ],
}

export function translateSearchKeys(t, keys = []) {
    return keys
        .map((key) => {
            const value = t(key)
            return value === key ? '' : value
        })
        .filter(Boolean)
}

export function stringsMatchQuery(strings, query) {
    const q = String(query ?? '').trim().toLowerCase()
    if (!q) {
        return false
    }

    return strings.some((value) => String(value ?? '').toLowerCase().includes(q))
}

export function tabSearchValues(tabId, t, extras = []) {
    return [
        tabId,
        ...translateSearchKeys(t, PREFERENCE_TAB_I18N_KEYS[tabId] ?? []),
        ...extras.filter(Boolean),
    ]
}
